"""Adicionando coluna documentos

Revision ID: 8dc25c28da47
Revises: 
Create Date: 2025-03-20 10:36:39.347405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dc25c28da47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documentos', sa.PickleType(), nullable=True))
        batch_op.alter_column('data',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.alter_column('apresentacao',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('agendamento',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('tipo_operacao',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('numero_bs',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('numero_nf',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('transportadora',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('tipo_veiculo',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('placa_cavalo',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('placa_carreta',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('numero_container',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.drop_column('doc3')
        batch_op.drop_column('doc2')
        batch_op.drop_column('doc4')
        batch_op.drop_column('doc1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc1', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('doc4', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('doc2', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('doc3', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('numero_container',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('placa_carreta',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('placa_cavalo',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('cpf',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=11),
               nullable=True)
        batch_op.alter_column('tipo_veiculo',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('transportadora',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('numero_nf',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('numero_bs',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('tipo_operacao',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('agendamento',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('apresentacao',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('data',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
        batch_op.drop_column('documentos')

    # ### end Alembic commands ###
